# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		Ramnath
tagline:	'blog'
description:	'Random Ramblings'
url:		http://github.com/ramnathv

author:
  name:		'Ramnath Vaidyanathan'
  url:		https://twitter.com/ramnath_vaidya

paginate:	5

# Custom vars
ico: /assets/images/slidify_logo_small.ico
icon:		/assets/images/slidify_logo_small.png
cover:		/assets/images/data_science.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/ramnath_vaidya
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/ramnathv
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	https://google.com/+ramnath.vaidya
    desc:	Add me on google+

  - icon:	feed
    url:	http://camporez.com/atom.xml
    desc:	Subscribe to my feed
    
menu:
  - title:	Home
    url:	http://camporez.com
    
  - title:	About
    url:	http://camporez.com/about
    
copyright:
  author:	Ramnath Vaidyanathan
  url:		http://camporez.com
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
